name: 'Upload repo packages'
description: 'Upload Ubuntu/Debian packages to JetHome repository'
inputs:
  user:
    required: false
    default: 'repo'
  hostname:
    required: false
    description: 'hostname of the repo site'
    default: 'repo.jethome.ru'
  hostpath:
    required: true
    description: 'path to the repo'
    default: '/home/repo/armbian'
  distro:
    required: true
    description: 'repositories to add packages'
  branch:
    required: true
    description: 'release type (stable, nightly, test)'
    default: 'test'
  path:
    required: true
    description: 'path to the packages'
    default: '.'
  files:
    required: true
    description: 'list of packages to upload'
  SSH_KEY:
    required: true
    description: 'SSH key for repo storage'
  SSH_KNOWNHOSTS_UPLOAD:
    required: true
    description: 'SSH known hosts for repo storage'

outputs:
  status:
    description: "result repo push"
    value: ${{ steps.deploy-to-repo-storage.outputs.output }}

runs:
  using: "composite"
  steps:
    - name: "Generate key id" # We need this in case we run multiple runners on one machine
      id: genkey
      shell: bash
      run: |
        echo "RANDOM=ID_$((RANDOM%1000000))" >> $GITHUB_ENV
        echo "HOME=${HOME}" >> $GITHUB_ENV
        mkdir -p ${HOME}/.ssh

    - name: Install SSH key for storage
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.SSH_KEY }}
        name: ${{ env.RANDOM }}
        known_hosts: unnecessary
        if_key_exists: replace
        config: |
          Host bastion
            HostName repo.jethome.ru
            User repo
            IdentityFile ${HOME}/.ssh/${{ env.RANDOM }}

    - name: Deploy to repo storage
      id: deploy-to-repo-storage
      shell: bash
      run: |
        if [ "${{ inputs.branch }}" == "stable" ]; then
          DEPLOYFOLDER=${{ inputs.hostpath }}
        elif [ "${{ inputs.branch }}" == "nightly" ]; then
          DEPLOYFOLDER=${{ inputs.hostpath }}-beta
        elif [ "${{ inputs.branch }}" == "test" ]; then
          DEPLOYFOLDER=${{ inputs.hostpath }}-test
        else
          echo 'output=not_need' >> $GITHUB_OUTPUT
          exit 0
        fi
        for dist in $(echo ${{ inputs.distro }} | sed 's/,/ /g'); do
          ssh -o StrictHostKeyChecking=no -i ${HOME}/.ssh/${{ env.RANDOM }} ${{ inputs.user }}@${{ inputs.hostname }} "mkdir -p ${DEPLOYFOLDER}/${dist}"
          files=$(echo "${{ inputs.files }}" | tr '\n' ' ')
          CURDIR=$(pwd)
          cd "${{ inputs.path }}"
          for file in $(ls ${files}); do
            rsync -e "ssh -o StrictHostKeyChecking=no -i ${HOME}/.ssh/${{ env.RANDOM }}" -avr ${file} ${{ inputs.user }}@${{ inputs.hostname }}:${DEPLOYFOLDER}/${dist}
          done
          cd ${CURDIR}
        done

        echo 'output=ok' >> $GITHUB_OUTPUT
        exit 0
